name: Selenide CI

on:
  workflow_dispatch:
    inputs:
      test-suite:
        description: 'Select Suite (Choose "custom" to use the text box below)'
        required: true
        default: 'ui'
        type: choice
        options:
        - ui
        - api
        - custom
      custom_command:
        description: 'Type mvn arguments (e.g., -Dtest=MyTest -Dtestng.suite.name=checkly-automation-ui)'
        required: false
        default: ''
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment: playwright-test

    steps:
      - uses: actions/checkout@v4 

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        env:
            AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
            ACC_ID: ${{ secrets.ACC_ID }}
            USER_GOKUL: ${{ secrets.USER_GOKUL }}
            GOKUL_PASSWORD: ${{ secrets.GOKUL_PASSWORD }}
        run: |
          if [ "${{ github.event.inputs.test-suite }}" == "ui" ]; then
            echo "Running UI tests..."
            mvn clean test -DsuiteXmlFiles=checkly-ui.xml -Dselenide.headless=true -Dselenide.screenshots=true
          elif [ "${{ github.event.inputs.test-suite }}" == "api" ]; then
            echo "Running API tests..."
            mvn clean test -DsuiteXmlFiles=checkly-api.xml 
          elif [ "${{ github.event.inputs.test-suite }}" == "custom" ]; then
            if [ -z "${{ github.event.inputs.custom_command }}" ]; then
              echo "Error: Custom option selected but no command provided."
              exit 1
            fi
            echo "Running custom command: ${{ github.event.inputs.custom_command }}"
              ${{ github.event.inputs.custom_command }}
          fi

      - name: Generate Allure Report
        if: always()
        run: |
          ## This converts the raw JSON in allure-results into a viewable HTML report
          # mvn allure:report
          # Use the full groupId and artifactId to avoid the "prefix" error
          mvn io.qameta.allure:allure-maven:2.17.0:report


      - name: Upload Allure Results (Raw Data)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # IMPORTANT: allure:report generates the HTML in target/site/allure-maven-plugin
          publish_dir: ./target/site/allure-maven-plugin